// <auto-generated />
using System;
using FindBook.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FindBook.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327140430_UpdateSavedAddressOwnershipKey")]
    partial class UpdateSavedAddressOwnershipKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FindBook.Core.Delivery.DeliveryTaskAggregate.DeliveryTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AssignedAt");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CompletedAt");

                    b.Property<int>("DeliveryPartnerAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("DeliveryPartnerAccountId");

                    b.Property<int>("RentalId")
                        .HasColumnType("integer")
                        .HasColumnName("RentalId");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPartnerAccountId");

                    b.HasIndex("RentalId");

                    b.ToTable("DeliveryTasks", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.Feedback.BookReviewAggregate.BookReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("BookId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Content");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("Rating");

                    b.Property<int>("ReviewerAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("ReviewerAccountId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Title");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("ReviewerAccountId");

                    b.HasIndex("BookId", "ReviewerAccountId")
                        .IsUnique();

                    b.ToTable("BookReviews", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.BookAggregate.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Author");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryId");

                    b.Property<string>("CoverImageReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("CoverImageUrl");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("Description");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Isbn");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("LibraryId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Isbn")
                        .IsUnique();

                    b.HasIndex("LibraryId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.BookAggregate.BookImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("BookId");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ContentType");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedOn");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("Data");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("FileName");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeInBytes");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BookImages", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.CategoryAggregate.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.LibraryAggregate.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ContactEmail");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ContactPhone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.Rental.RentalAggregate.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("BookId");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("LibraryId");

                    b.Property<DateOnly?>("ReturnRequestedOn")
                        .HasColumnType("date")
                        .HasColumnName("ReturnRequestedOn");

                    b.Property<DateOnly?>("ReturnedOn")
                        .HasColumnType("date")
                        .HasColumnName("ReturnedOn");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.UserManagement.UserAccountAggregate.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("FullName");

                    b.Property<int?>("ManagedLibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("ManagedLibraryId");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);
                });

            modelBuilder.Entity("FindBook.Core.Delivery.DeliveryTaskAggregate.DeliveryTask", b =>
                {
                    b.OwnsOne("FindBook.Core.SharedKernel.DeliveryAddressSnapshot", "DeliveryAddress", b1 =>
                        {
                            b1.Property<int>("DeliveryTaskId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryCountry");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DeliveryPostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("DeliveryStreet");

                            b1.HasKey("DeliveryTaskId");

                            b1.ToTable("DeliveryTasks");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryTaskId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.BookAggregate.Book", b =>
                {
                    b.OwnsOne("FindBook.Core.LibraryInventory.BookAggregate.BookRatingSummary", "RatingSummary", b1 =>
                        {
                            b1.Property<int>("BookId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("AverageRating")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("AverageRating");

                            b1.Property<int>("RatingCount")
                                .HasColumnType("integer")
                                .HasColumnName("RatingCount");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.OwnsOne("FindBook.Core.LibraryInventory.BookAggregate.InventoryState", "InventoryState", b1 =>
                        {
                            b1.Property<int>("BookId")
                                .HasColumnType("integer");

                            b1.Property<int>("AvailableCopies")
                                .HasColumnType("integer")
                                .HasColumnName("AvailableCopies");

                            b1.Property<int>("TotalCopies")
                                .HasColumnType("integer")
                                .HasColumnName("TotalCopies");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.Navigation("InventoryState")
                        .IsRequired();

                    b.Navigation("RatingSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.BookAggregate.BookImage", b =>
                {
                    b.HasOne("FindBook.Core.LibraryInventory.BookAggregate.Book", null)
                        .WithOne()
                        .HasForeignKey("FindBook.Core.LibraryInventory.BookAggregate.BookImage", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FindBook.Core.LibraryInventory.LibraryAggregate.Library", b =>
                {
                    b.OwnsOne("FindBook.Core.SharedKernel.PostalAddress", "Address", b1 =>
                        {
                            b1.Property<int>("LibraryId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("Street");

                            b1.HasKey("LibraryId");

                            b1.ToTable("Libraries");

                            b1.WithOwner()
                                .HasForeignKey("LibraryId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("FindBook.Core.Rental.RentalAggregate.Rental", b =>
                {
                    b.OwnsOne("FindBook.Core.SharedKernel.DeliveryAddressSnapshot", "DeliveryAddress", b1 =>
                        {
                            b1.Property<int>("RentalId")
                                .HasColumnType("integer");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryCountry");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DeliveryPostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("DeliveryState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("DeliveryStreet");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.OwnsOne("FindBook.Core.Rental.RentalAggregate.RentalPeriod", "RentalPeriod", b1 =>
                        {
                            b1.Property<int>("RentalId")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("DueOn")
                                .HasColumnType("date")
                                .HasColumnName("DueOn");

                            b1.Property<DateOnly>("RentedOn")
                                .HasColumnType("date")
                                .HasColumnName("RentedOn");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("RentalPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("FindBook.Core.UserManagement.UserAccountAggregate.UserAccount", b =>
                {
                    b.OwnsMany("FindBook.Core.UserManagement.UserAccountAggregate.SavedAddress", "SavedAddresses", b1 =>
                        {
                            b1.Property<int>("UserAccountId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("Id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<bool>("IsDefault")
                                .HasColumnType("boolean")
                                .HasColumnName("IsDefault");

                            b1.HasKey("UserAccountId", "Id");

                            b1.ToTable("SavedAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");

                            b1.OwnsOne("FindBook.Core.SharedKernel.PostalAddress", "Address", b2 =>
                                {
                                    b2.Property<int>("SavedAddressUserAccountId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SavedAddressId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("Country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("PostalCode");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("character varying(100)")
                                        .HasColumnName("State");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(250)
                                        .HasColumnType("character varying(250)")
                                        .HasColumnName("Street");

                                    b2.HasKey("SavedAddressUserAccountId", "SavedAddressId");

                                    b2.ToTable("SavedAddresses");

                                    b2.WithOwner()
                                        .HasForeignKey("SavedAddressUserAccountId", "SavedAddressId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("SavedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
